### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by djromero** [lambdalisue/fern-bookmark.vim#1]
Error during neovim startup:
```
Error detected while processing /home/djromero/.local/share/nvim/plugged/fern-bookmark.vim/plugin/fern_bookmark.vim:
line    6:
E121: Undefined variable: g:fern#mapping#mappings
E116: Invalid arguments for function extend
```
And the bookmarks scheme doesn't work.

The relevant part of the configuration:
```
Plug 'lambdalisue/fern.vim'
Plug 'lambdalisue/fern-renderer-devicons.vim'
Plug 'lambdalisue/fern-bookmark.vim'

let g:fern#renderer = "devicons"
nnoremap <Leader>t :Fern . -drawer -reveal=%<CR> " open tree drawer and reveal current file
nnoremap <Leader>x :Fern %:h -reveal=%<CR>       " browse current files' directory
```

Before adding the bookmarks plugin it worked fine.

Neovim version: NVIM v0.5.0-360-g1f479fffb

**Comment by djromero** [comment]
Right after creating the issue I saw there were changes in the last 24 hours...it's solved now after updating Fern. 
I wonder if this situation can be detected (version mismatch between fern and one of its subplugins) to show a custom error message.

Sorry for the noise.

**Comment by lambdalisue** [comment]
> I wonder if this situation can be detected (version mismatch between fern and one of its subplugins) to show a custom error message.

At least not for now. Maybe I'll consider this after v1.
