### ISSUE TITLE
g:fern#scheme#bookmark#store#file does not exist by default and is not document in the repo readme

### ISSUE THREAD

**Issue by Gremious** [lambdalisue/fern-bookmark.vim#9]
My init.vim has both

```vim
	Plug 'lambdalisue/fern.vim'
	Plug 'lambdalisue/fern-bookmark.vim'
```
If I open any file in neovim, e.g. my `init.vim` and execute `:Fern bookmark:///` I get an empty Fern window. 
Executing `:messages` gives the following:

```vim
[fern] ERROR: Vim(let):E121: Undefined Variable: g:fern#scheme#bookmark#store#file
```

This also shows up if I open Fern normally and press `B` to bookmark - no text in the status-line, and that error message shows in `:messages`.

This can be resolved by adding 
```vim
let g:fern#scheme#bookmark#store#file = "~/.fern/bookmark.json"
```
to the vim config.

However, this variable is said to already have a default value of `"~/.fern/bookmark.json"` in the helpfile, and as such, I'm inclined to say this is probably a bug. Also, the GitHub readme only mentions the other variable.

Please consider checking up on that, and if it is intentional, I would like to suggest adding a message to the help-file and repository readme that users need to set it, as it is not necessarily obvious by default.

**Comment by lambdalisue** [comment]
That should be initialized on https://github.com/lambdalisue/fern-bookmark.vim/blob/39d533393dc302ba4cf52dd7fa10268d6f9dd4b0/autoload/fern/scheme/bookmark/store.vim#L17-L19

So I wonder which plugin manager do you use and how.

**Comment by Gremious** [comment]
I use vim plug, installed in the way [it suggests](https://github.com/junegunn/vim-plug#neovim) for neovim, e.g. 

```bash
sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
```

Then, in my `~/.config/nvim/init.vim` I do  `source ~/.config/nvim/plugins.vim`, which itself has:
```vim
call plug#begin(stdpath('data') . '/plugged')
	" == snip ==

	Plug 'ryanoasis/vim-devicons'
	" File Tree
	Plug 'lambdalisue/nerdfont.vim'
	Plug 'lambdalisue/glyph-palette.vim'
	Plug 'lambdalisue/fern-renderer-nerdfont.vim'
	Plug 'lambdalisue/fern.vim'
	Plug 'lambdalisue/fern-git-status.vim'
	Plug 'lambdalisue/fern-bookmark.vim'
	Plug 'lambdalisue/fern-mapping-project-top.vim'

	" == snip ==
call plug#end()

" In Fern (filetree) show colored icons
augroup my-glyph-palette
	autocmd! *
	autocmd FileType fern call glyph_palette#apply()
	autocmd FileType nerdtree,startify call glyph_palette#apply()
augroup END
let g:fern#renderer = "nerdfont"

" make it work
let g:fern#scheme#bookmark#store#file = "~/.fern/bookmark.json"
```

I don't have an `init_fern()` or anything, as it seems to work fine by default, perhaps I missed some necessary setup step?

**Comment by lambdalisue** [comment]
Do you place Vim plugins in symlink or so on? I wonder the result of `expand('<sfile>:p')` what I pointed before.

**Comment by Gremious** [comment]
Ah, sorry

No, plugins aren't symlinked or anything, just in `~/.local/share/nvim/plugged/`

I added a `let g:fern_test = expand('<sfile>:p')` to the `store.vim`, right before the call

doing `echo fern_test` gives:
`/home/<Username>/.local/share/nvim/plugged/fern-bookmark.vim/autoload/fern/scheme/bookmark/store.vim` which is the correct place of that file, it exists

**Comment by lambdalisue** [comment]
Hum... I'm not sure but does #10 solves the issue?

**Comment by Gremious** [comment]
Yep, can confirm that works fine!
